title: Tony Deep's Blogs
name: TonyKhanh
author: TonyKhanh
twitter_username: TVKhanh_ICTU
baseurl: "/"
description: &description "Science with a spirit of adventure"
profile_url: "http://tonydeep.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
