title: Tony Deep's Blogs
name: "Tony Khanh"
author: Tony Khanh
twitter_username: TVKhanh_ICTU
baseurl: "/"
description: Science with a spirit of adventure.
profile_url: "http://tonydeep.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
